CREATE TABLE  AGENTS (	
    AGENT_CODE CHAR(6) NOT NULL PRIMARY KEY, 
	AGENT_NAME CHAR(40), 
	WORKING_AREA CHAR(35), 
	COMMISSION DOUBLE(10,2), 
	PHONE_NO CHAR(15), 
	COUNTRY CHAR(25) 
);

CREATE TABLE  CUSTOMER (	
    CUST_CODE CHAR(6) NOT NULL PRIMARY KEY, 
	CUST_NAME CHAR(40) NOT NULL, 
	CUST_CITY CHAR(35), 
	WORKING_AREA CHAR(35) NOT NULL, 
	CUST_COUNTRY CHAR(20) NOT NULL, 
	GRADE DOUBLE, 
	OPENING_AMT DOUBLE(12,2) NOT NULL, 
	RECEIVE_AMT DOUBLE(12,2) NOT NULL, 
	PAYMENT_AMT DOUBLE(12,2) NOT NULL, 
	OUTSTANDING_AMT DOUBLE(12,2) NOT NULL, 
	PHONE_NO CHAR(17) NOT NULL, 
	AGENT_CODE CHAR(6) NOT NULL REFERENCES AGENTS
);

CREATE TABLE  ORDERS (
    ORD_NUM DOUBLE(6,0) NOT NULL PRIMARY KEY, 
	ORD_AMOUNT DOUBLE(12,2) NOT NULL, 
	ADVANCE_AMOUNT DOUBLE(12,2) NOT NULL, 
	ORD_DATE DATE NOT NULL, 
	CUST_CODE CHAR(6) NOT NULL REFERENCES CUSTOMER, 
	AGENT_CODE CHAR(6) NOT NULL REFERENCES AGENTS, 
	ORD_DESCRIPTION CHAR(60) NOT NULL
);